[package]
name = "rustgrep"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
owo-colors = "4.1.0"
regex = "1.10.6"
tempfile = "3.13.0"
uuid = { version = "1.10.0", features = ["v4"] }
